experiment_name: "tes-mol"
checkpoint_dir: "checkpoints_mol"

data:
  size: 512
  batch_size: 1
  prompts_file: "data/prompts.txt"
  tasks:
    canny:
      weight: 0.2
      target_dir: "data/canny/targets"
      cond_dir: "data/canny/conditions"
    depth:
      weight: 0.8
      target_dir: "data/canny/targets"
      cond_dir: "data/canny/conditions"

training:
  num_epochs: 1
  learning_rate: 1.0e-5
  weight_decay: 1.0e-2
  save_every_n_steps: 0